# Generated by Django 5.0.2 on 2025-03-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_admission_letter_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admission_letter',
            field=models.FileField(blank=True, null=True, upload_to='documents/admission_letters/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/id_documents/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to='documents/transcripts/'),
        ),
    ]
