# Generated by Django 5.0.2 on 2025-03-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_id_document_verified_user_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='program_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
