# Generated by Django 5.0.2 on 2025-03-19 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_enrollment_course_alter_enrollment_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='accounts.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('to_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='accounts.course')),
            ],
        ),
    ]
