# Generated by Django 5.0.2 on 2025-03-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_coursetransferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_transferable',
            field=models.BooleanField(default=True),
        ),
    ]
