# Generated by Django 5.0.2 on 2025-03-22 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_pickuplocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('slip_file', models.FileField(blank=True, null=True, upload_to='registration_slips/')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_slips', to='accounts.courseapproval')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_slips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
