# Generated by Django 5.0.2 on 2025-03-22 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_registrationslip'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('course_enrolled', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=50)),
                ('tuition_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('library_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('laboratory_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hostel_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('examination_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medical_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
