# Generated by Django 5.0.2 on 2025-03-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_feespayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feespayment',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
